insert into db_senac.tbl_senac(nome,email,senha) values ('carlos','carlos@gmail.com','123456');


INSERT INTO db_senac.tbl_senac(nome, email, senha) VALUES 
('Ana', 'ana@example.com', 'password1'),
('Bruno', 'bruno@example.com', 'password2'),
('Carla', 'carla@example.com', 'password3'),
('Daniel', 'daniel@example.com', 'password4'),
('Eva', 'eva@example.com', 'password5'),
('Fernando', 'fernando@example.com', 'password6'),
('Gabriela', 'gabriela@example.com', 'password7'),
('Hugo', 'hugo@example.com', 'password8'),
('Isabela', 'isabela@example.com', 'password9'),
('João', 'joao@example.com', 'password10'),
('Katia', 'katia@example.com', 'password11'),
('Lucas', 'lucas@example.com', 'password12'),
('Mariana', 'mariana@example.com', 'password13'),
('Nando', 'nando@example.com', 'password14'),
('Olga', 'olga@example.com', 'password15'),
('Pedro', 'pedro@example.com', 'password16'),
('Quiteria', 'quiteria@example.com', 'password17'),
('Rafael', 'rafael@example.com', 'password18'),
('Sofia', 'sofia@example.com', 'password19'),
('Thiago', 'thiago@example.com', 'password20'),
('Ursula', 'ursula@example.com', 'password21'),
('Vera', 'vera@example.com', 'password22'),
('William', 'william@example.com', 'password23'),
('Xuxa', 'xuxa@example.com', 'password24'),
('Yara', 'yara@example.com', 'password25'),
('Zé', 'ze@example.com', 'password26'),
('André', 'andre@example.com', 'password27'),
('Bianca', 'bianca@example.com', 'password28'),
('Carlos', 'carlos@example.com', 'password29'),
('Débora', 'debora@example.com', 'password30'),
('Eduardo', 'eduardo@example.com', 'password31'),
('Fernanda', 'fernanda@example.com', 'password32'),
('Gustavo', 'gustavo@example.com', 'password33'),
('Helena', 'helena@example.com', 'password34'),
('Igor', 'igor@example.com', 'password35'),
('Juliana', 'juliana@example.com', 'password36'),
('Kaio', 'kaio@example.com', 'password37'),
('Lúcia', 'lucia@example.com', 'password38'),
('Marco', 'marco@example.com', 'password39'),
('Natália', 'natalia@example.com', 'password40'),
('Otávio', 'otavio@example.com', 'password41'),
('Patrícia', 'patricia@example.com', 'password42'),
('Quincas', 'quincas@example.com', 'password43'),
('Roberta', 'roberta@example.com', 'password44'),
('Samira', 'samira@example.com', 'password45'),
('Tânia', 'tania@example.com', 'password46'),
('Ulisses', 'ulisses@example.com', 'password47'),
('Vanessa', 'vanessa@example.com', 'password48'),
('Walter', 'walter@example.com', 'password49'),
('Xander', 'xander@example.com', 'password50'),
('Yuri', 'yuri@example.com', 'password51'),
('Zilda', 'zilda@example.com', 'password52'),
('Adriana', 'adriana@example.com', 'password53'),
('Brenda', 'brenda@example.com', 'password54'),
('Cláudio', 'claudio@example.com', 'password55');


select *
from db_senac.tbl_senac